<?php

namespace Richpolis\ElbuenBurguesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UbicacionesesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionesRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT MAX(p.posicion) as value 
            FROM ElbuenBurguesBundle:Ubicaciones p 
            ORDER BY p.createdAt ASC
            ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function getQueryUbicacionesActivas($todas=false){
        $query=$this->createQueryBuilder('p')
                    ->orderBy('p.createdAt', 'DESC');
        return $query->getQuery();
    }
    
    public function getUbicacionesActivas($todas=false){
        $query=$this->getQueryUbicacionesActivas($todas);
        return $query->getResult();
    }
    
    public function getUltimaUbicacion()
    {
        $resultados=$this->getUbicacionesActivas();
        if($resultados!=null){
            return $resultados[0];
        }else{
            return null;
        }
    }
    
    public function getRegistroUpOrDown($posicionRegistro,$up=true){
        // $up = true, $up = false is down
        if($up){
            //up
            $query=$this->createQueryBuilder('p')
                    ->where('p.posicion>:posicion')
                    ->setParameter('posicion', $posicionRegistro)
                    ->orderBy('p.posicion', 'DESC');
        }else{
            //down
            $query=$this->createQueryBuilder('p')
                    ->where('p.posicion<:posicion')
                    ->setParameter('posicion', $posicionRegistro)
                    ->orderBy('p.posicion', 'DESC');
        }
        
        return $query->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }
    
}